/*
Jose Angel Prado Dupont A01373243
Andrea Margarita Pérez Barrera A01373631
*/
namespace INT64 {

    enum TokenCategory {
        BREAK,
        CASE,
        CONTINUE,
        DEFAULT,
        DO,
        FALSE,
        ELSE,
        FOR,
        IF,
        IN,
        RETURN,
        SWITCH,
        TRUE,
        WHILE,
        VAR,
        COMMENT,
        STRING,
        LONGCOMMENT,
        NEWLINE,
        IDENTIFIER,
        BINARYINT,
        OCTALINT,
        HEXAINT,
        INTEGER,
        CHARACTER,
        PLUS,
        MINUS,
        LESS,
        MORE,
        OPENB,
        CLOSEB,
        OPENP,
        CLOSEP,
        SEMICOLON,
        COMA,
        ASIGNATION,
        OR,
        AND,
        COLON,
        INTERROGATION,
        EQUAL,
        NOTEQUAL,
        LESSEQUAL,
        MOREEQUAL,
        ORR,
        POWER,
        ANDD,
        SHIFTL,
        SHIFTR,
        SHIFTT,
        TIMES,
        DIV,
        REM,
        POWERR,
        EXCLAMATION,
        FLOW,
        EOF,
        ERROR
    }
}

